### PR TITLE
Fix style in coretoolhost Project

### LINKED ISSUE #4320: Fix warnings in the repository
Build.csproj and test/ projects can be ignored for now.

There will be a lot of file changes so this should be done incrementally over several PRs (maybe 30 files per PR max).

- [x] Func project
- [x] Host project
- [x] Artifact Assembler Project

### PR DESCRIPTION
**Pull request by VineethReyya**
### Issue describing the changes in this PR
fixing style issues in coretoolhost project

Partially resolves #4320

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: src/CoreToolsHost/AppLoader/HostFxr.cs [hunk 1]
```diff
@@ -1,48 +1,45 @@
...
+            StringMarshalling = StringMarshalling.Utf16)]
 #endif
-        )]
         public static partial int SetAppContextData(IntPtr host_context_handle, string name, string value);
 
         [LibraryImport("hostfxr", EntryPoint = "hostfxr_close")]
         public static partial int Close(IntPtr host_context_handle);
+
+        #pragma warning disable CS0649
+        public unsafe struct Hostfxr_initialize_parameters
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:37]: @aishwaryabh you added the host project, do you know if we need to keep the lowercase format for these methods and props i.e. `hostfxr_initialize_parameters`

Comment (aishwaryabh) [reply src/CoreToolsHost/AppLoader/HostFxr.cs:37]: Just checked with Shyju since he implemented the .NET custom host and we don't need to keep the lowercase format for methods and props

Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:37]:
```suggestion
        public unsafe struct HostFXRInitializeParameters
```

File: src/CoreToolsHost/AppLoader/HostFxr.cs [hunk 2]
```diff
@@ -1,48 +1,45 @@
...
-            StringMarshalling = StringMarshalling.Utf16
+            StringMarshalling = StringMarshalling.Utf16)]
 #endif
-        )]
         public static partial int SetAppContextData(IntPtr host_context_handle, string name, string value);
 
         [LibraryImport("hostfxr", EntryPoint = "hostfxr_close")]
         public static partial int Close(IntPtr host_context_handle);
+
+        #pragma warning disable CS0649
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:36]: remove warning pragma

File: src/CoreToolsHost/AppLoader/NetHost.cs [hunk 3]
```diff
@@ -1,34 +1,24 @@
...
-
-            // Optional.Path to the application assembly,
-            // If specified, hostfxr is located from this directory if present (For self-contained deployments)
-            public char* assembly_path;
-            public char* dotnet_root;
-        }
-
         [DllImport("nethost", CharSet = CharSet.Auto)]
-        private unsafe static extern int get_hostfxr_path(
+        private static extern unsafe int Get_hostfxr_path(
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/NetHost.cs:11]:
```suggestion
        private static extern unsafe int GetHostFXRPath(
```

File: src/CoreToolsHost/AppLoader/HostFxr.cs [hunk 4]
```diff
@@ -1,48 +1,45 @@
 ﻿// Copyright (c) .NET Foundation. All rights reserved.
-// Licensed under the MIT License. See License.txt in the project root for license information.
+// Licensed under the MIT License. See LICENSE in the project root for license information.
 
 using System.Runtime.InteropServices;
 
 namespace CoreToolsHost
 {
-    static partial class HostFxr
+    public static partial class HostFxr
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:8]: the default if not provided is internal, so this should be internal

File: src/CoreToolsHost/AppLoader/HostFxr.cs [hunk 5]
```diff
@@ -1,48 +1,45 @@
...
 #endif
-        )]
-        public unsafe static partial int Initialize(
+        public static unsafe partial int Initialize(
             int argc,
             string[] argv,
             IntPtr parameters,
-            out IntPtr host_context_handle
-        );
+            out IntPtr host_context_handle);
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:20]:
```suggestion
            out IntPtr hostContextHandle);
```

**Review by liliankasem — CHANGES_REQUESTED** [review]

File: src/CoreToolsHost/AppLoader/HostFxr.cs (hunk 2 above)
Comment (VineethReyya) [reply src/CoreToolsHost/AppLoader/HostFxr.cs:36]: @liliankasem Thanks for the feedback. we get this below warning if we remove warning pragma:
 warning CS0649: Field 'HostFxr.HostFXRInitializeParameters.DotnetRoot' is never assigned to, and will always have its default value

Comment (liliankasem) [reply src/CoreToolsHost/AppLoader/HostFxr.cs]: Hmm I see, lets leave for now then

**Review by liliankasem — APPROVED** [review]

**Review by umangsriv — APPROVED** [review]
