### PR TITLE
Fix flakey tests

### LINKED ISSUE #4545: Fix flakey tests
There are a couple flakey tests that should be addressed.

**Unit**

- [HostHelperTests](https://github.com/Azure/azure-functions-core-tools/blob/main/test/Cli/Func.UnitTests/HelperTests/HostHelperTests.cs)
  - My guess is it's something to do with the file system access 

**E2E**

- Any `func new` test for workers that use bundles
  - The failure is on: `Templates JSON is empty. Please check the templates location.`
  - This is coming from the templates manager [here](https://github.com/Azure/azure-functions-core-tools/blob/e963a7607b71a06d8cd2780833c5487fa50c511c/src/Cli/func/Common/TemplatesManager.cs#L88) or [here](https://github.com/Azure/azure-functions-core-tools/blob/e963a7607b71a06d8cd2780833c5487fa50c511c/src/Cli/func/Common/TemplatesManager.cs#L297)

[Here's](https://azfunc.visualstudio.com/public/_build/results?buildId=228472&view=logs&j=da439e82-8265-5962-85f8-172d6600cb6f&t=17f2655d-abad-5398-83c4-ac47d6b8119e) a CI run that shows both of these failures.

### PR DESCRIPTION
**Pull request by liliankasem**
### Issue describing the changes in this PR

resolves #4545

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs [hunk 1]
```diff
@@ -59,6 +60,8 @@ public static async Task GetExtensionBundle()
             }
             catch (Exception)
             {
+                ColoredConsole.WriteLine("Failed to download the Extension Bundle. Please check your network connection and try again.");
```
Comment (kshyju) [inline src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs]: Should we wrap the network call in a retry mechanism so that a transient network issue is not throwing the error?

File: src/Cli/func/Common/TemplatesManager.cs [hunk 2]
```diff
@@ -69,7 +69,10 @@ private static async Task<IEnumerable<Template>> GetTemplates()
             var extensionBundleManager = ExtensionBundleHelper.GetExtensionBundleManager();
             string templatesJson;
 
-            if (extensionBundleManager.IsExtensionBundleConfigured())
+            var configured = extensionBundleManager.IsExtensionBundleConfigured();
+            ColoredConsole.WriteLine("extensionBundleManager.IsExtensionBundleConfigured() = " + configured);
```
Comment (kshyju) [inline src/Cli/func/Common/TemplatesManager.cs]: Will users see this message in their terminal? Should this be behind the verbose flag?

Comment (liliankasem) [reply src/Cli/func/Common/TemplatesManager.cs]: Sorry this is just for me debugging the issue, not intended to be merged.

**Review by aishwaryabh — APPROVED** [review]

File: src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs [hunk 3]
```diff
@@ -49,13 +55,23 @@ public static string GetBundleDownloadPath(string bundleId)
         public static async Task GetExtensionBundle()
         {
             var extensionBundleManager = GetExtensionBundleManager();
+            var bundlePath = await extensionBundleManager.GetExtensionBundlePath();
+
+            if (Directory.Exists(bundlePath) && Directory.GetFiles(bundlePath, "*", SearchOption.AllDirectories).Any())
```
Comment (aishwaryabh) [inline src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs]: should we write a quick unit test for this use case?

Comment (liliankasem) [reply src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs]: done!

Comment (liliankasem) [reply src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs]: Actualy removing this code because `await extensionBundleManager.GetExtensionBundlePath();` already does this

File: test/Cli/Func.UnitTests/HelperTests/ExtensionBundleHelperTests.cs [hunk 4]
```diff
@@ -1,7 +1,12 @@
 ﻿// Copyright (c) .NET Foundation. All rights reserved.
 // Licensed under the MIT License. See LICENSE in the project root for license information.
 
+using System.IO.Abstractions;
```
Comment (aishwaryabh) [inline test/Cli/Func.UnitTests/HelperTests/ExtensionBundleHelperTests.cs]: do we need these dependencies?

Comment (liliankasem) [reply test/Cli/Func.UnitTests/HelperTests/ExtensionBundleHelperTests.cs]: nope, leftovers from the changes I undid - I'll remove them!

File: src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs [hunk 5]
```diff
@@ -49,13 +55,17 @@ public static string GetBundleDownloadPath(string bundleId)
...
             var extensionBundleManager = GetExtensionBundleManager();
+
             try
             {
-                using (var httpClient = new HttpClient())
-                {
-                    httpClient.Timeout = TimeSpan.FromMinutes(10);
-                    await extensionBundleManager.GetExtensionBundlePath(httpClient);
-                }
+                using var httpClient = new HttpClient { Timeout = _httpTimeout };
```
Comment (kshyju) [inline src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs:61]: The `GetExtensionBundle` method is called from `StartHostAction.RunAsync`. I am wondering that a 10 minute HTTP timeout might be too long. If the request hangs, users running `func host start` command could be left waiting without feedback and may think the CLI is unresponsive. Since we already have retries in place, maybe we could consider reducing the timeout to fail faster and improve the user experience?

File: src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs [hunk 6]
```diff
@@ -25,7 +25,11 @@ public override async Task RunAsync()
             {
                 try
                 {
-                    string bundlePath = await extensionBundleManager.GetExtensionBundlePath();
+                    var options = ExtensionBundleHelper.GetExtensionBundleOptions();
```
Comment (kshyju) [inline src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs:28]: I thought `ExtensionBundleManager.GetExtensionBundlePath` was meant to be the single source of truth for getting the extension bundle path. Is there a reason we are not using it here? Is that method not returning the expected output in some scenarios? Trying to understand the switch to the new logic here.

File: .vscode/launch.json [hunk 7]
```diff
@@ -13,7 +13,7 @@
             },
             "args": "${input:funcArgs} --script-root ${input:scriptRootArg}",
             "cwd": "${workspaceFolder}/src/Cli/func",
-            "console": "internalConsole",
+            "console": "integratedTerminal",
```
Comment (kshyju) [inline .vscode/launch.json:16]: Is this change unrelated to flaky test fix?

File: src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs (hunk 5 above)
Comment (liliankasem) [reply src/Cli/func/ExtensionBundle/ExtensionBundleHelper.cs:61]: good point, I'll lower it to maybe 2-3 mins?

File: src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs (hunk 6 above)
Comment (liliankasem) [reply src/Cli/func/Actions/LocalActions/GetExtensionBundlePath.cs:28]: The problem is that `GetExtensionBundlePath` will also install templates if they don't exist. Given this action is just to return the path itself it doesn't make sense for it to also download the bundles. I believe this is also one of the contributors for the flakeyness happening in the e2e tests. 

Second, `GetExtensionBundlePath` uses the download path that it gets from core tools so this is just shortcuriting all the download bundle stuff that we don't need here.

File: .vscode/launch.json (hunk 7 above)
Comment (liliankasem) [reply .vscode/launch.json:16]: No, just an enhacement for the repro in general - didn't feel like it was worth its own pr

**Review by aishwaryabh — APPROVED** [review]
