### PR TITLE
Use Muxer from .NET SDK for dotnet discovery

### LINKED ISSUE #4725: Azure DevOps: Azure Functions Core Tools Can't Find .NET 10 Installed by UseDotNet@2 Task on Windows Agents
### Version

I was upgrading an Azure Durable Function Application from `.NET 9` to `.NET 10`. Our Azure DevOps pipeline have a job that executes set of integration tests by spinning up the function using `func`. Since we were using `MSSQLLocalDB`, the agent is `Windows`.

After the upgrade, the integration tests was failing to spin up `func` with a frustrating error.
```
You must install or update .NET to run this application.
App: D:\a\1\s\tests\...\bin\Debug\net10.0\FunctionApp.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '10.0.0' (x64)
.NET location: C:\Program Files\dotnet\
The following frameworks were found:
  8.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.21 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  9.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  9.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 
Learn more:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
```

### Description

The pipeline used the [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines&WT.mc_id=DT-MVP-5000570) task to install `.NET 10`.
```yaml
- task: UseDotNet@2
  displayName: Install .NET 10.0.x
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
```
The pipeline debug logs showed [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines&WT.mc_id=DT-MVP-5000570) task was setting `DOTNET_ROOT` and updating `PATH` correctly:
```
##[debug]Absolute path for pathSegments: C:\hostedtoolcache\windows\dotnet\sdk
Successfully installed .NET Core sdk version 10.0.100.
##[debug]Processed: ##vso[task.prependpath]C:\hostedtoolcache\windows/dotnet
##[debug]set DOTNET_ROOT=C:\hostedtoolcache\windows/dotnet
```

And `dotnet --info` confirmed `.NET 10` was installed.
Image

However `func.exe` doesn't seem to recognize it, it kept looking at  `C:\Program Files\dotnet`. 
When starting the worker process, it ignores:
* The `DOTNET_ROOT` environment variable
* The `PATH` environment variable

Since `.NET 10` isn't yet pre-installed on DevOps agents, Azure Functions can't find it.

Shouldn't `func` consider `DOTNET_ROOT` or `PATH` to determine `dotnet`?

### Workaround:

When installing `.NET 10`, override the default installation path which is `$(Agent.ToolsDirectory)/dotnet`  (`C:\hostedtoolcache\windows\dotnet` in `Windows`) to `C:\Program Files\dotnet` where Azure Functions expects to find it.
```
- task: UseDotNet@2
  displayName: Install .NET 10.0.x
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
    installationPath: 'C:\Program Files\dotnet'
```

### Steps to reproduce

- Spin up a .NET 10 function app using `func` in an Azure DevOps Pipeline that runs on `windows-latest`
- Install .NET SDK
```
- task: UseDotNet@2
  displayName: Install .NET 10.0.x
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
```

### PR DESCRIPTION
**Pull request by liliankasem**
### Issue describing the changes in this PR

resolves #4725, #3285

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Replace CommandChecker.CommandExists with DotnetMuxer class copied from the .NET SDK to improve dotnet installation discovery. This provides more comprehensive detection using multiple fallback strategies including DOTNET_HOST_PATH, DOTNET_ROOT, and process path resolution.

Changes:
- Add DotnetMuxer and FileNameSuffixes helper classes from dotnet/sdk
- Update EnsureDotnet() to use DotnetMuxer.MuxerPath with better error handling
- Remove multi-TFM conditionals since CLI only targets net8.0
- Improve error message to include all discoverable environment variables

### CODE REVIEW

File: src/Cli/func/Helpers/DotnetMuxer.cs [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+            if (File.Exists(muxerPathMaybe))
+            {
+                _muxerPath = muxerPathMaybe;
+            }
+        }
+
+        if (_muxerPath is null)
+        {
+            // Best-effort search for muxer.
+            // SDK sets DOTNET_HOST_PATH as absolute path to current dotnet executable
```
Comment (jviau) [inline src/Cli/func/Helpers/DotnetMuxer.cs:41]: This comment looks out of place?

File: src/Cli/func/Helpers/FileNameSuffixes.cs
Comment (jviau) [inline src/Cli/func/Helpers/FileNameSuffixes.cs:1]: Is this file used anywhere?

File: test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+            // Arrange & Act
+            var muxer = new DotnetMuxer();
+
+            // Assert
+            Assert.NotNull(muxer.MuxerPath);
+            Assert.False(string.IsNullOrWhiteSpace(muxer.MuxerPath));
+        }
+
+        [Fact]
+        public void MuxerPath_ThrowsInvalidOperationException_WhenNotFound()
```
Comment (jviau) [inline test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs]: This isn't testing anything. I recommend removing this if we can't actually test it.

File: test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+
+            // If we got here, dotnet was found (which is expected in test environment)
+            Assert.NotNull(muxer.MuxerPath);
+        }
+
+        [Fact]
+        public void MuxerName_IsCorrect()
+        {
+            // Assert
+            Assert.Equal("dotnet", DotnetMuxer.MuxerName);
```
Comment (jviau) [inline test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs]: This test doesn't add much value. Recommend removing it.

File: test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+            {
+                Assert.Equal(string.Empty, DotnetMuxer.ExeSuffix);
+            }
+        }
+
+        [Fact]
+        public void GetDataFromAppDomain_ReturnsNull_ForNonExistentKey()
+        {
+            // Act
+            var result = DotnetMuxer.GetDataFromAppDomain("NON_EXISTENT_KEY_12345");
```
Comment (jviau) [inline test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs]: Nit: not sure this has much value for being separately testable either. You are testing a 1 line proxy to a runtime API. We can assume the runtime API is already tested.

File: test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+
+            // Act
+            var path = muxer.MuxerPath;
+
+            // Assert
+            Assert.Contains("dotnet", path, StringComparison.OrdinalIgnoreCase);
+        }
+
+        [Fact]
+        public void MuxerPath_PointsToExecutableFile()
```
Comment (jviau) [inline test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs]: Maybe we can actually invoke the `dotnet` exe with something like `--version` arg to assert this in fact `dotnet` executable that was found.

File: src/Cli/func/Helpers/DotnetMuxer.cs (hunk 1 above)
Comment (liliankasem) [reply src/Cli/func/Helpers/DotnetMuxer.cs:41]: Ah I removed some of the TFM switch regions so this is outdated, let me update!

File: src/Cli/func/Helpers/DotnetMuxer.cs [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+
+public class DotnetMuxer
+{
+    public static readonly string MuxerName = "dotnet";
+
+    private readonly string _muxerPath;
+
+    public static readonly string ExeSuffix = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ".exe" : string.Empty;
+
+    public DotnetMuxer()
```
Comment (jviau) [inline src/Cli/func/Helpers/DotnetMuxer.cs]: Having this be a class doesn't seem to offer much here. I understand this is a copy & paste, but I would assume they made it a class to fit their needs (capturing of the lookup result or exception).

The usage in this PR has this class instantiated each time `.MuxerPath` is accessed. This could be a static function in that case.

File: src/Cli/func/Helpers/FileNameSuffixes.cs
Comment (liliankasem) [reply src/Cli/func/Helpers/FileNameSuffixes.cs:1]: Yeah line 24 in Muxer:

`string muxerPathMaybe = Path.Combine(rootPath, $"{MuxerName}{FileNameSuffixes.CurrentPlatform.Exe}");`

File: test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs (hunk 2 above)
Comment (liliankasem) [reply test/Cli/Func.UnitTests/HelperTests/DotnetMuxerTests.cs]: This is what happens when you have copilot write tests! I'll remove the ones that don't make sense

File: src/Cli/func/Helpers/DotnetMuxer.cs (hunk 6 above)
Comment (liliankasem) [reply src/Cli/func/Helpers/DotnetMuxer.cs]: Agree that static makes sense, we can revist this + DI during our refactor work.

File: src/Cli/func/Helpers/FileNameSuffixes.cs
Comment (liliankasem) [reply src/Cli/func/Helpers/FileNameSuffixes.cs:1]: No longer used - removed from codebase

**Review by jviau — APPROVED** [review]

File: src/Cli/func/Helpers/DotnetMuxer.cs [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+            }
+        }
+
+        if (muxerPath is null)
+        {
+            throw new InvalidOperationException("Unable to locate dotnet multiplexer");
+        }
+
+        return muxerPath;
+    }
```
Comment (jaliyaudagedara) [inline src/Cli/func/Helpers/DotnetMuxer.cs:60]: I am sorry, too much nesting makes it a bit harder to read, early returns would make it more readable.

Something like,
```csharp
public static string GetMuxerPath()
{
    string muxerPath;

    // Most scenarios are running dotnet.dll as the app
    // Root directory with muxer should be two above app base: <root>/sdk/<version>
    string rootPath = Path.GetDirectoryName(Path.GetDirectoryName(AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar)));
    if (rootPath is not null)
    {
        muxerPath = Path.Combine(rootPath, $"{_muxerName}{_exeSuffix}");
        if (File.Exists(muxerPath))
        {
            return muxerPath;
        }
    }

    // Best-effort search for muxer.
    muxerPath = Environment.ProcessPath;

    // The current process should be dotnet in most normal scenarios except when dotnet.dll is loaded in a custom host like the testhost
    if (muxerPath is not null && Path.GetFileNameWithoutExtension(muxerPath).Equals("dotnet", StringComparison.OrdinalIgnoreCase))
    {
        return muxerPath;
    }

    // SDK sets DOTNET_HOST_PATH as absolute path to current dotnet executable
    muxerPath = Environment.GetEnvironmentVariable("DOTNET_HOST_PATH");
    if (muxerPath is not null)
    {
        return muxerPath;
    }

    // Fallback to DOTNET_ROOT which typically holds some dotnet executable
    string root = Environment.GetEnvironmentVariable("DOTNET_ROOT");
    if (root is not null)
    {
        muxerPath = Path.Combine(root, $"dotnet{_exeSuffix}");
        return muxerPath;
    }
   
    throw new InvalidOperationException("Unable to locate dotnet executable");
}
```

Changed the exception message for easy understanding `Unable to locate dotnet executable`.

**Review by aishwaryabh — APPROVED** [review]

File: src/Cli/func/Helpers/DotnetMuxer.cs (hunk 7 above)
Comment (liliankasem) [reply src/Cli/func/Helpers/DotnetMuxer.cs:60]: Thanks for the suggestion! I'd like to keep this implementation close to the .NET SDK's original structure to make it easier to track upstream changes and ensure we maintain the same behavior. As for the error message, the end user ends up with this error message which should be easy to understand:

`Unable to locate the .NET SDK. Install the .NET SDK from https://aka.ms/dotnet-download or configure PATH | DOTNET_ROOT | DOTNET_HOST_PATH so that 'dotnet' is discoverable`

Comment (jaliyaudagedara) [reply src/Cli/func/Helpers/DotnetMuxer.cs:60]: Of course, understood!

Comment (liliankasem) [reply src/Cli/func/Helpers/DotnetMuxer.cs:60]: Actually had a change of heart on this, I want to support more areas where dotnet would be so at this point it does make sense to clean up for readability as we keep adding on: https://github.com/Azure/azure-functions-core-tools/pull/4738
