### PR TITLE
Fix locale-sensitive version parsing causing .NET 10 publish failures

### LINKED ISSUE #4794: v4.7.0 regression: publish fails for .NET 10 Isolated on Flex Consumption
### Version

4.7.0

### Description

`func azure functionapp publish` fails on v4.7.0 when deploying a .NET 10 Isolated app to a Flex Consumption plan. The `-dotnet-version 10.0` flag is ignored. The same command  works on v4.6.0.

Error (v4.7.0):

> No target framework version detected from project. Keeping existing Azure runtime configuration. You are deploying .NET Isolated to Flex consumption. Flex consumpton supports .NET 10.0, 9.0, 8.0. Please upgrade your app to an appropriate .NET version and try the deployment again.

Here is how the azure function is configured:
``` sh
az resource show \
    --ids $(az functionapp show --name <app-name> --resource-group <rg-name> --query id --output tsv) \
    --query "{kind: kind, properties: properties.functionAppConfig}" \
    --output json
```

``` json
{
  "kind": "functionapp,linux",
  "properties": {
    "deployment": {
      "storage": {
        "authentication": {
          "storageAccountConnectionStringName": null,
          "type": "systemassignedidentity",
          "userAssignedIdentityResourceId": null
        },
        "type": "blobcontainer",
        "value": "https://<redacted>.blob.core.windows.net/<redacted>"
      }
    },
    "runtime": {
      "name": "dotnet-isolated",
      "version": "10.0"
    },
    "scaleAndConcurrency": {
      "alwaysReady": null,
      "instanceMemoryMB": 2048,
      "maximumInstanceCount": 100,
      "triggers": null
    },
    "siteUpdateStrategy": {
      "type": "Recreate"
    }
  }
}
```

It's unclear if `4.7.0` was intentionally published to https://www.npmjs.com/package/azure-functions-core-tools/v/4.7.0 because there is no corresponding release in this repo https://github.com/Azure/azure-functions-core-tools/releases

### Steps to reproduce

  1. `npm i -g azure-functions-core-tools@4.7.0`
  2. `dotnet publish` a .NET 10 Isolated Functions project to an output directory
  3. From that directory: `func azure functionapp publish <app-name> --dotnet-isolated --dotnet-version 10.0`
  4. Observe error response
  5. Install 4.6.0: `npm i -g azure-functions-core-tools@4.6.0`
  6. Redploy: `func azure functionapp publish <app-name> --dotnet-isolated --dotnet-version 10.0`
  7. Deployment succeeds

### PR DESCRIPTION
**Pull request by liliankasem**
### Issue describing the changes in this PR

resolves #4794

### Additional information

- Root cause: `double.TryParse` without `CultureInfo.InvariantCulture` in two version-parsing methods. In locales where `.` is a thousands separator (e.g., `fr-FR`, `de-DE`), the string `"10.0"` (extracted from TFM `"net10.0"`) is interpreted as `100`, causing `_requiredNetFrameworkVersion` to be set to `"100.0"` and failing Flex SKU validation.
- Fix: pass `NumberStyles.Float` and `CultureInfo.InvariantCulture` to both `double.TryParse` call sites

### Testing

Tested with:

- `func azure functionapp publish func-fileresourcemcpserver --dotnet-isolated --dotnet-version 10.0`
- `func azure functionapp publish func-fileresourcemcpserver --dotnet-isolated --dotnet-version 9.0`
- `func azure functionapp publish func-fileresourcemcpserver --dotnet-isolated --dotnet-version 8.0`

### CODE REVIEW

File: src/Cli/func/Helpers/StacksApiHelper.cs [hunk 1]
```diff
@@ -41,7 +42,7 @@ public static WindowsRuntimeSettings GetRuntimeSettings(this FunctionsStacks sta
             }
 
             var versionStr = dotnetVersionFromConfig?.ToLower()?.Replace("net", string.Empty);
-            if (double.TryParse(versionStr, out double version))
+            if (double.TryParse(versionStr, NumberStyles.Float, CultureInfo.InvariantCulture, out double version))
```
Comment (aishwaryabh) [inline src/Cli/func/Helpers/StacksApiHelper.cs:45]: can we add a quick test for this?

**Review by aishwaryabh — APPROVED** [review]
