### PR TITLE
Notify of `CONTAINER_NAME` being a protected environment variable

### LINKED ISSUE #4227: func start errors when there is a CONTAINER_NAME app setting
### Version

4.0.6610

### Description

When running locally via `func start` and there is a settings key named `CONTAINER_NAME`, the host fails to start with an error like this

```
2025-01-10T18:49:46.653Z] A host error has occurred during startup operation '93b5a6ad-ec94-4ec1-ba40-6ea947e3d854'.
[2025-01-10T18:49:46.658Z] Microsoft.AspNetCore.DataProtection: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. Microsoft.AspNetCore.DataProtection: The key ring does not contain a valid default protection key. The data protection system cannot create a new key because auto-generation of keys is disabled. For more information go to https://aka.ms/aspnet/dataprotectionwarning.
```
or in another example this error:

```
MS_FUNCTION_LOGS 5,,,,,ScriptApplicationHostOptionsSetup,"","ScmRunFromPackage is empty.",4.1036.1.23224,2025-01-10T19:19:44.1367206Z,,"",,,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Workers Directory set to: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers",4.1036.1.23224,2025-01-10T19:19:44.3978729Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\java\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.3984380Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.3995780Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: java",4.1036.1.23224,2025-01-10T19:19:44.4001866Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: java','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4074404Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4083169Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: node",4.1036.1.23224,2025-01-10T19:19:44.4085027Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: node','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4088870Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4096310Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: powershell",4.1036.1.23224,2025-01-10T19:19:44.4096555Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: powershell','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4098235Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4104689Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: python",4.1036.1.23224,2025-01-10T19:19:44.4104966Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: python','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\OneDrive\source\repos\deleteme\fail_func\bin\output\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4107190Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4114375Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME_VERSION: ",4.1036.1.23224,2025-01-10T19:19:44.4120122Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Added WorkerConfig for language: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4130035Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Workers Directory set to: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers",4.1036.1.23224,2025-01-10T19:19:44.4131665Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\java\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4133707Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4141432Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: java",4.1036.1.23224,2025-01-10T19:19:44.4141642Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: java','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4143358Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4149209Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: node",4.1036.1.23224,2025-01-10T19:19:44.4149419Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: node','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4150634Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4156767Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: powershell",4.1036.1.23224,2025-01-10T19:19:44.4156966Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: powershell','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4158448Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4162818Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: python",4.1036.1.23224,2025-01-10T19:19:44.4163004Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated. Skipping WorkerConfig for language: python','category':'Host.LanguageWorkerConfig','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: C:\Users\mimcke\OneDrive\source\repos\deleteme\fail_func\bin\output\worker.config.json",4.1036.1.23224,2025-01-10T19:19:44.4165481Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4172050Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME_VERSION: ",4.1036.1.23224,2025-01-10T19:19:44.4172695Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Added WorkerConfig for language: dotnet-isolated",4.1036.1.23224,2025-01-10T19:19:44.4173482Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,,Host.Triggers.Warmup,"","Initializing Warmup Extension.",4.1036.1.23224,2025-01-10T19:19:44.4671607Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'Initializing Warmup Extension.','category':'Host.Triggers.Warmup','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,,Microsoft.Azure.WebJobs.Host.IDistributedLockManager,"","Using BlobLeaseDistributedLockManager",4.1036.1.23224,2025-01-10T19:19:44.4831451Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 4,,,,Initializing,Host.Startup,"","Initializing Host. OperationId: 'f1392de7-1d45-4527-ad5b-0f2028437c4b'.",4.1036.1.23224,2025-01-10T19:19:44.4997146Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'Initializing Host. OperationId: f1392de7-1d45-4527-ad5b-0f2028437c4b.','category':'Host.Startup','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364,'eventId':503,'eventName':'Initializing'}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 4,,,,Initialization,Host.Startup,"","Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=f1392de7-1d45-4527-ad5b-0f2028437c4b",4.1036.1.23224,2025-01-10T19:19:44.5053157Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=f1392de7-1d45-4527-ad5b-0f2028437c4b','category':'Host.Startup','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364,'eventId':504,'eventName':'Initialization'}",RAW,,1/10/2025 7:19:44 PM
MS_FUNCTION_LOGS 5,,,,LogHostInitializationSettings,Host.Startup,"","{   'OriginalFunctionWorkerRuntime': 'dotnet-isolated',   'FunctionsWorkerRuntime': 'dotnet-isolated',   'OriginalFunctionWorkerRuntimeVersion': null,   'FunctionsWorkerRuntimeVersion': null,   'FunctionsExtensionVesion': null,   'HostDirectory': 'C:\\Users\\mimcke\\OneDrive\\source\\repos\\deleteme\\fail_func\\bin\\output',   'InStandbyMode': false,   'HasBeenSpecialized': false,   'UsePlaceholderDotNetIsolated': false,   'WebSiteSku': null,   'FeatureFlags': null,   'HostingConfig': {},   'HISMode': 'Disabled' }",4.1036.1.23224,2025-01-10T19:19:44.5381752Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_LOGS 2,,,,,Host.Startup,"","Unable to load the functions payload since the app was not provisioned with valid AzureWebJobsStorage connection string.",4.1036.1.23224,2025-01-10T19:19:44.5384806Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 2,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'Unable to load the functions payload since the app was not provisioned with valid AzureWebJobsStorage connection string.','category':'Host.Startup','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Error','levelId':4,'processId':5364}",RAW,,1/10/2025 7:19:44 PM
[2025-01-10T19:19:44.538Z] Unable to load the functions payload since the app was not provisioned with valid AzureWebJobsStorage connection string.
MS_FUNCTION_LOGS 4,,,,FunctionMetadataManagerLoadingFunctionsMetadata,Host.Startup,"","Loading functions metadata",4.1036.1.23224,2025-01-10T19:19:44.5530248Z,,"",,f3f013ad-7efe-452a-b409-57a1256ad93b,,RAW,,,,
MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'raw','message':'Loading functions metadata','category':'Host.Startup','hostVersion':'4.1036.1.23224','hostInstanceId':'f3f013ad-7efe-452a-b409-57a1256ad93b','level':'Information','levelId':2,'processId':5364,'eventId':314,'eventName':'FunctionMetadataManagerLoadingFunctionsMetadata'}",RAW,,1/10/2025 7:19:44 PM
[2025-01-10T19:19:44.573Z] Error while assigning execute permission.
[2025-01-10T19:19:44.574Z] Mono.Posix.NETStandard: Unable to find an entry point named 'Mono_Posix_Syscall_getcwd' in DLL 'MonoPosixHelper'.
```

If this settings key is renamed, such as in my example `RAW_CONTAINER_NAME`, this error goes away.

### Steps to reproduce

To reproduce the first error, build this GitHub repo: https://github.com/mmckechney/semantic_kernel_askq. This code has a function project named `DocumentQuestionsFunction`. When there is a local.settings.json key of `CONTAINER_NAME` it gives the `DataProtection` error. 

For the second error, you can create a new function project using:
``` bash
func init --worker-runtime dotnet-isolated --target-framework net8.0
func function new --language C# --template blobtrigger --name funcRepro
```

edit the `local.settings.json` file to add a new item `CONTAINER_NAME` and add any value, but don't leave it empty

then start the function with `func start` and you will experience the second error.

### PR DESCRIPTION
**Pull request by liliankasem**
### Issue describing the changes in this PR

resolves #4227

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Let users know that `CONTAINER_NAME` is a protected environment variable until there are changes in the host to move away from this practice.

### CODE REVIEW

File: src/Cli/func/Actions/HostActions/StartHostAction.cs [hunk 1]
```diff
@@ -203,6 +203,11 @@ private async Task<IWebHost> BuildWebHost(ScriptApplicationHostOptions hostOptio
             _keyVaultReferencesManager.ResolveKeyVaultReferences(settings);
             UpdateEnvironmentVariables(settings);
 
+            if (settings.ContainsKey("CONTAINER_NAME")) // && !RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ?
+            {
+                throw new CliException("CONTAINER_NAME is a reserved environment variable for the Functions Host. Please remove or rename this setting.");
```
Comment (liliankasem) [inline src/Cli/func/Actions/HostActions/StartHostAction.cs]: Maybe too aggressive and should just warn instead.

File: src/Cli/func/Actions/HostActions/StartHostAction.cs [hunk 2]
```diff
@@ -203,6 +203,14 @@ private async Task<IWebHost> BuildWebHost(ScriptApplicationHostOptions hostOptio
             _keyVaultReferencesManager.ResolveKeyVaultReferences(settings);
             UpdateEnvironmentVariables(settings);
 
+            // Should we also check for "!RuntimeInformation.IsOSPlatform(OSPlatform.Linux)"? Who sets CONTAINER_NAME in Functions on Linux?
+            // Can we allow for this to be set in linux environments?
+            if (settings.ContainsKey("CONTAINER_NAME"))
```
Comment (kshyju) [inline src/Cli/func/Actions/HostActions/StartHostAction.cs:206]: Similar to `CONTAINER_NAME`, the host code depends on several other environment variables. Are we planning to handle all of them individually?

Rather than applying a fix in core tools, I suggest addressing the broader issue of using overly generic env variable names in the host and related components. Ideally, these variables should follow a function specific naming convention/prefix (e.g., `FUNCTIONS_CONTAINER_NAME`). This may require coordination with other component owners and take some time, but it would be a cleaner and more sustainable solution.

Comment (liliankasem) [reply src/Cli/func/Actions/HostActions/StartHostAction.cs:206]: @kshyju - I agree, we should address this in the host - I actually already creted an issue for this long term:

https://github.com/Azure/azure-functions-host/issues/11222

But in the mean time I don't think it hurts to warn folks about this in the CLI, there are a couple of other env vars like you mentioned, but this one seems to be the one that pops up the most for folks which is why I am adding a note about it.

**Review by aishwaryabh — APPROVED** [review]
