### PR TITLE
Fix warnings in solution (excluding build csproj)

### LINKED ISSUE #4320: Fix warnings in the repository
Build.csproj and test/ projects can be ignored for now.

There will be a lot of file changes so this should be done incrementally over several PRs (maybe 30 files per PR max).

- [x] Func project
- [x] Host project
- [x] Artifact Assembler Project

### PR DESCRIPTION
**Pull request by VineethReyya**
### Issue describing the changes in this PR

Fix warnings in the project

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by VineethReyya** [comment]
@aishwaryabh @liliankasem when you have a moment, please review the changes.

File: src/CoreToolsHost/AppLoader/HostFxr.cs [hunk 1]
```diff
@@ -12,6 +12,13 @@ public unsafe struct hostfxr_initialize_parameters
             public nint size;
             public char* host_path;
             public char* dotnet_root;
+
+            public hostfxr_initialize_parameters()
```
Comment (liliankasem) [inline src/CoreToolsHost/AppLoader/HostFxr.cs:16]: What was the warning here? Wondering if we should suppress or not

File: src/Cli/func/Telemetry/ExternalTelemetryProperties.cs [hunk 2]
```diff
@@ -24,17 +24,14 @@ internal static class ExternalTelemetryProperties
...
-            }
-
             const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion";
             const string ValueName = @"InstallationType";
 
             try
             {
-                return (string)Registry.GetValue(Key, ValueName, defaultValue: "");
+                return RuntimeInformation.IsOSPlatform(OSPlatform.Windows) 
+                    ? Registry.GetValue(Key, ValueName, defaultValue: "") as string
```
Comment (liliankasem) [inline src/Cli/func/Telemetry/ExternalTelemetryProperties.cs:33]:
```suggestion
                    ? Registry.GetValue(Key, ValueName, defaultValue: string.Empty) as string
```

File: src/CoreToolsHost/AppLoader/HostFxr.cs (hunk 1 above)
Comment (VineethReyya) [reply src/CoreToolsHost/AppLoader/HostFxr.cs:16]: @liliankasem this is the error:
error CS0649: Field 'HostFxr.hostfxr_initialize_parameters.dotnet_root' is never assigned to, and will always have its default value

File: src/Cli/func/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs [hunk 3]
```diff
@@ -16,9 +16,10 @@ namespace Azure.Functions.Cli.Actions.HostActions.WebHost.Security
 {
     public class CliAuthenticationHandler<TOptions> : AuthenticationHandler<TOptions> where TOptions : AuthenticationSchemeOptions, new()
     {
-        public CliAuthenticationHandler(IOptionsMonitor<TOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) 
-            : base(options, logger, encoder, clock)
+        public CliAuthenticationHandler(IOptionsMonitor<TOptions> options, ILoggerFactory logger, UrlEncoder encoder, TimeProvider timeProvider) 
+            : base(options, logger, encoder)
```
[the remark this answers is not in the document]
Comment (VineethReyya) [reply src/Cli/func/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs:20]: @liliankasem ISystemClock clock is obsolete, so we need to use timeprovider

 base constructor for that is from namespace Microsoft.AspNetCore.Authentication:
image

File: src/CoreToolsHost/AppLoader/HostFxr.cs (hunk 1 above)
Comment (liliankasem) [reply src/CoreToolsHost/AppLoader/HostFxr.cs:16]: lets supress this for now and undo the change here

File: src/Cli/func/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (liliankasem) [reply src/Cli/func/Actions/HostActions/WebHost/Security/CliAuthenticationHandler.cs:20]: I think we can remove clock here completely i.e.

`public CliAuthenticationHandler(IOptionsMonitor<TOptions> options, ILoggerFactory logger, UrlEncoder encoder)`

**Comment by liliankasem** [comment]
@VineethReyya just FYI that I fixed the build props and artifactassembler.cs files in my last 2 commits

**Comment by liliankasem** [comment]
> > @VineethReyya just FYI that I fixed the build props and artifactassembler.cs files in my last 2 commits
> 
> @liliankasem Thanks for the commits. I just commit few changes. could you please review.
> 
> Also tried to supress : NU5118 because in .csproj [line no 298](https://github.com/Azure/azure-functions-core-tools/blob/main/src/Cli/func/Azure.Functions.Cli.csproj#L298) we are trying to include the same file under two different PackagePaths. and also using both a wildcard include (***) and an explicit file include (**main**.py), image
> 
> The issue can be resolved by removing the conflicting paths, but I’ve temporarily suppressed it until I receive your suggestion.

Lets keep supressed for now.

File: build/Build.csproj [hunk 4]
```diff
@@ -9,4 +9,9 @@
     <PackageReference Include="WindowsAzure.Storage" />
     <PackageReference Include="Newtonsoft.Json" />
   </ItemGroup>
+
+  <!-- setting directly to false as this project will be deprecated soon -->
+  <PropertyGroup>
+    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
```
Comment (aishwaryabh) [inline build/Build.csproj:15]: can you fix the spacing for this please?

File: eng/Directory.Build.Common.props [hunk 5]
```diff
@@ -21,11 +21,11 @@
...
+    <NoWarn>$(NoWarn);NU5118</NoWarn>
   </PropertyGroup>
 
-  <!-- uncomment this in a new PR and fix all errors -->
-  <!-- https://github.com/Azure/azure-functions-core-tools/issues/4320 -->
-  <!-- <PropertyGroup>
-    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
-  </PropertyGroup> -->
+  <PropertyGroup>
+    <TreatWarningsAsErrors>false</TreatWarningsAsErrors> <!-- TODO:// set to true for CI builds only -->
```
Comment (aishwaryabh) [inline eng/Directory.Build.Common.props:29]: can you fix the spacing for this please?

**Review by aishwaryabh — APPROVED** [review]

File: eng/Directory.Build.Common.props (hunk 5 above)
Comment (liliankasem) [reply eng/Directory.Build.Common.props:29]: What's the space issue? it looks normal to me

Comment (aishwaryabh) [reply eng/Directory.Build.Common.props:29]: oh wait nvm I think I was looking at a diff commit XD
