### PR TITLE
Fix python buildenv dockerfile name

### LINKED ISSUE #4740: `func pack --build-native-deps` fails for Python 3.13+ when running on Windows
### Version

4.4.0+

### Description

Running `func pack --build-native-deps` for Python 3.13+ on a Windows machine throws an error saying that: 
```
The directory name is invalid. : 'C:\Users\victoriahall\AppData\Local\Temp\azure-functions\python:4-python3.13-buildenv-docker'
```
I also tested with CT version 4.5.0 and got the same error. This only seems to happen with Windows - Mac seems to work as expected.

Full output:
```
(.venv313) PS C:\Users\victoriahall\Documents\repos\sdk-servicebus> func pack --build-native-deps
'local.settings.json' found in root directory (C:\Users\victoriahall\Documents\repos\sdk-servicebus).
Resolving worker runtime to 'python'.
'local.settings.json' found in root directory (C:\Users\victoriahall\Documents\repos\sdk-servicebus).
Resolving worker runtime to 'python'.

Validating project...

  Validate host.json: PASSED
  Validate Flag Compatibility: PASSED
  Validate Folder Structure: PASSED
  Validation .python_packages directory exists: WARNING
    Directory '.python_packages' not found or is empty.
  Validate Python Programming Model: PASSED

The directory name is invalid. : 'C:\Users\victoriahall\AppData\Local\Temp\azure-functions\python:4-python3.13-buildenv-docker'
(.venv313) PS C:\Users\victoriahall\Documents\repos\sdk-servicebus> func --version
4.4.0
```

### Steps to reproduce

1. On a Windows machine, download Python 3.13 & create a 3.13 environment
2. Start Docker
3. Run `func pack --build-native-deps` in the terminal

### PR DESCRIPTION
**Pull request by liliankasem**
### Issue describing the changes in this PR

resolves #4740

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Tested on Windows:

```log
PS C:\Users\likasem\Desktop\pythonapp313> & $env:FUNC_CLI --version
4.5.0-dev
PS C:\Users\me\Desktop\pythonapp313> & $env:FUNC_CLI pack --build-native-deps
'local.settings.json' found in root directory (C:\Users\me\Desktop\pythonapp313).
Resolving worker runtime to 'python'.
'local.settings.json' found in root directory (C:\Users\me\Desktop\pythonapp313).
Resolving worker runtime to 'python'.

Validating project...

  Validate host.json: PASSED
  Validate Flag Compatibility: PASSED
  Validate Folder Structure: PASSED
  Validation .python_packages directory exists: WARNING
    Directory '.python_packages' not found or is empty.
  Validate Python Programming Model: PASSED

Deleting the old .python_packages directory
Running 'docker build -t azure-functions/python:4-python313-buildenv C:\Users\me\AppData\Local\Temp\4-python313-buildenv'..done
Running 'docker exec -t e5085f chmod +x /python_docker_build.sh'..done
Running 'docker exec -t e5085f /python_docker_build.sh'....done
Running 'docker cp e5085f:"/.python_packages/." "C:\Users\me\Desktop\pythonapp313\.python_packages"'..done
Running 'docker kill e5085f'..done
Creating a new package C:\Users\me\Desktop\pythonapp313\pythonapp313.zip
```

Tested on OSX:

```log
> $FUNC_CLI -v
4.5.0-dev
> $FUNC_CLI pack --build-native-deps
'local.settings.json' found in root directory (/Users/me/python313app).
Resolving worker runtime to 'python'.
'local.settings.json' found in root directory (/Users/me/python313app).
Resolving worker runtime to 'python'.

Validating project...

  Validate host.json: PASSED
  Validate Flag Compatibility: PASSED
  Validate Folder Structure: PASSED
  Validation .python_packages directory exists: WARNING
    Directory '.python_packages' not found or is empty.
  Validate Python Programming Model: PASSED

Running 'docker build -t azure-functions/python:4-python313-buildenv /var/folders/g4/zmwjmq3j3vq7g9x4yflrrwg40000gn/T/4-python313-buildenv'.....done
Running 'docker exec -t dfdf12 chmod +x /python_docker_build.sh'..done
Running 'docker exec -t dfdf12 /python_docker_build.sh'....done
Running 'docker cp dfdf12:"/.python_packages/." "/Users/me/python313app/.python_packages"'..done
Running 'docker kill dfdf12'..done
Creating a new package /Users/me/python313app/python313app.zip
```

### CODE REVIEW

File: src/Cli/func/Helpers/PythonHelpers.cs [hunk 1]
```diff
@@ -564,10 +564,11 @@ private static async Task<DockerImageInfo> ChoosePythonBuildEnvImage()
             {
                 // Setup image tag and content
                 string imageContent = image;
-                image = $"azure-functions/python:4-python{workerInfo.Major}.{workerInfo.Minor}-buildenv";
+                string dockerfileName = $"4-python{workerInfo.Major}{workerInfo.Minor}-buildenv";
```
Comment (aishwaryabh) [inline src/Cli/func/Helpers/PythonHelpers.cs:567]: should we add a test just to make sure that this doesn't change in the future with any potential refactors?

Comment (liliankasem) [reply src/Cli/func/Helpers/PythonHelpers.cs:567]: done!

**Review by aishwaryabh — APPROVED** [review]
